inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [barcode]
- alias:  fileformat
  values: [ docx, pptx, xlsx ]

generationRules:
  include:
  - fileformat[docx, pptx, xlsx]
  
outputPath: "assembly\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
