inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [table]
- alias:  fileformat
  values: [ pdf ]

generationRules:
  include:
  - fileformat[pdf]
  
outputPath: "assembly\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
